### ISSUE TITLE
Bukkit/Spigot sent me

### ISSUE THREAD

**Issue by sawarahh** [EvModder/DropHeads#107]
This error comes up frequently:

```
06.02 07:04:19 [Server] WARN Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
06.02 07:04:19 [Server] INFO Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
06.02 07:04:19 [Server] INFO If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).
```

Every so often, all custom heads will glitch out. By glitch out, I mean when you break them, it drops an Alex head, and when you place them, it drops some other head with brown hair. A reset to the server seems to fix the issue, but only temporarily.

**Comment by EvModder** [comment]
The first issue (console error) is from 1.20.3+ (Spigot / Bukkit got a bit pickier about how plugins can set head textures)
It's fixed in the latest full-release jar from Dec 14:
https://dev.bukkit.org/projects/dropheads/files

The second issue is something I haven't heard about before - if it continues to happen after you update the plugin, could you try setting `async-offline-profile-requests: true` (or false if it is already `true`)?
I feel like that's the most likely candidate source for the issue.

**Comment by sawarahh** [comment]
I should have mentioned my server is still on 1.20.2! Will your latest file still work for me or should I wait until my server is up to date?

Thanks for your quick reply!

**Comment by EvModder** [comment]
Yep! Latest jar should work on any version 1.13-1.20.4

**Comment by sawarahh** [comment]
Hi there, I updated to the latest jar and changed `async-offline-profile-requests: true` (it was `false` before), but I'm still getting that error. It happened when I placed a regular cat mob head into the world. Any ideas?

Also totally separate comment... I would love to give players the ability to use `/headrate`, but it doesn't seem to be a valid permission when I've tried adding it in LuckPerms.

**Comment by EvModder** [comment]
I assume the "Found inconsistent skull meta" isn't occurring anymore, so you're referring to the custom head textures glitching out and getting replaced with Steve/Alex/[one of the other 7](https://minecraft.wiki/w/Skin#Default_skins) default skins added in 1.19

No one else has reported that issue, and since I'm not sure how to recreate it, all I have right now are 2 theories:
1) It's some compatibility issue with some other plugin that maybe "takes over" and overrides head/skin lookup.
2) Or your server lost connection to Mojang's API servers (where skin files are stored), or perhaps the ping is just very high so it timed out instead of returning the skin. I feel like if this was the case, after it stops working you'd start to see a lot of people getting the default skin when they log on as well (or getting "Invalid session"/"Authentication servers are down" error when connecting, or something similar)

Oh and for your separate comment: the permission node is [dropheads.droprate](https://github.com/EvModder/DropHeads/blob/32fb1005fb9b940eaccd1f85fcba7b4ec7b6aa6a/plugin.yml#L120C3-L120C21)
I'm working on adding some sub-permissions in v3.9.1 for editing droprates with the command instead of having to go through the file but I haven't finalized those yet. (default will be op-only, and LuckPerms is pretty good at respecting that so it should be safe to give players the parent permission)

**Comment by EvModder** [comment]
This should be now be fully fixed in [the latest release](https://dev.bukkit.org/projects/dropheads/files/5222173) of the plugin...

Sorry for the error lasting this long - I was having trouble recreating it, but @GrafterCrafter was very helpful in DMs and pointed out it happened after the plugin (or server) is reloaded/restarted, when the first person to log in has a DH head in their inventory
